# Generated by Django 4.2.10 on 2024-03-02 20:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("username", models.CharField(max_length=8, unique=True)),
                ("balance_halfdays", models.IntegerField(default=0)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Activating"), (2, "Active")],
                        default=0,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(db_index=True, max_length=10, unique=True)),
                ("total_count", models.IntegerField(default=0)),
                ("used_count", models.IntegerField(default=0, editable=False)),
                ("is_unlimited", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="VPNServer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ip", models.GenericIPAddressField(protocol="IPv4", unique=True)),
                ("visible_name", models.CharField(max_length=32, unique=True)),
                (
                    "ssh_user",
                    models.CharField(
                        default="virbox",
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z_]([a-z0-9_-]{0,31}|[a-z0-9_-]{0,30}\\$)$"
                            )
                        ],
                    ),
                ),
                ("ssh_port", models.PositiveIntegerField(default=22)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("n_days", models.IntegerField()),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "coupon",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="main.coupon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "payment_id",
                    models.BinaryField(
                        db_index=True,
                        default=main.models.Invoice.gen_payment_id,
                        unique=True,
                    ),
                ),
                (
                    "price_xmr",
                    models.DecimalField(decimal_places=12, default=0, max_digits=20),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.plan"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
